[project]
name = "factorsums"
version = "0.3.0"
description = "A project for prime partition generation using SageMath."
license = "MIT"
authors = [{ name = "Eric Page", email = "genamthi@gmail.com" }]
readme = "README.md"
requires-python = "~=3.12"
dependencies = []

[tool.pixi.pypi-options]
no-build-isolation = true

# --- Pixi Workspace and Environment Configuration ---

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = "~=3.12"
sage = ">=10.6,<11" 
numpy = "*"
psutil = "*"
tqdm = "*"
cython = "*"
setuptools = "*"

[tool.pixi.pypi-dependencies]
factorsums = { path = ".", editable = true }
