name = "factorsums"
version = "0.3.0"
description = "A project for factor sums calculations using SageMath"
readme = "README.md"
requires-python = "~=3.12"
dependencies = [] # No direct pip dependencies, all handled by micromamba

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"] # tells setuptools to look for packages in the 'src' directory

[tool.setuptools.package-data]
"factorsums" = ["data/*primes_*.csv"] # Dynamically named prime partition data files 